### ISSUE TITLE
Q&A Resolve & Replies

### ISSUE THREAD

**Issue by cqvu** [os-ucsd/workshop-facilitator#95]
## Tasks
- [ ] Add an option to resolve questions
- [ ] Add option to reply
- [ ] Modify schema to include replies in the q&a model

## Acceptance Criteria
- Each question needs a reply option
- Reply thread should be shown as a modal  and persist
- Each question needs a resolve option
- Resolved questions should go in the resolved tab

## Dependencies
N/A

## Resources
