### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by cqvu** [os-ucsd/workshop-facilitator#98]
## Tasks
- [ ] Decide on deployment platform
- [ ] Deploy the app
- [ ] Set up continuous deployment from main branch

## Acceptance Criteria
- Live app is deployed
- Pushing to main branch will automatically trigger a deployment update
